.TA c
.TH upgrade-ux 8
.ds )H GNU GPL v3
.ds ]W HP-UX Release 11i v1,2,3
.SH NAME
upgrade-ux \- a simple framework for new korn shell projects
.SH SYNOPSIS

.B upgrade-ux
.RB [ \-vhfs ]
.IR option ...
.br

.SH DESCRIPTION
The
.B upgrade-ux
project XYZ and so on
.B upgrade-ux
creates a nice HTML and plain ASCII documentation. If you like, write your description of the system into
.B some file

example:

