on:
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: To avoid fatal could not read Username
      run: |
          git config --global user.email "gdha@users.noreply.github.com"
          git config --global user.name "gdha"
          git config --global url.https://${{ secrets.GITHUB_TOKEN }}@github.com/
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:3.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
        FILENAME_PREFIX: ReleaseNotes
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        ACTION_MAIL: gdha@users.noreply.github.com
        ACTION_NAME: gdha
        GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        MD_FOLDER: temp_release_notes
        OWNER: gdha
        REPO_NAME: upgrade-ux
        SKIP_MD: README.md
