on: 
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
     - name: Upload Release Notes to Wiki
       uses: docker://decathlon/wiki-page-creator-action:2.0.1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         ACTION_MAIL: gratien.dhaese@gmail.com
         ACTION_NAME: gdha
         OWNER: gdha
         REPO_NAME: upgrade-ux
